spring:
    cloud:
        bus:
            trace:
                  enabled: true
        stream:
            kafka:
                binder:
                    zk-nodes: 10.6.71.51:2181
                    brokers: 10.6.71.51:9092
management:
    security:
        enabled: false