server:
    port: 8761

eureka:
    instance:
        hostname: 10.6.71.51
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/