spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/oauth?useUnicode=true&characterEncoding=utf8
        username: root
        password: test
        druid:
            minEvictableIdleTimeMillis: 300000
            testWhileIdle: true
            testOnBorrow: true
            testOnReturn: false
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 20
            filters: stat,wall,log4j
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            useGlobalDataSourceStat: true