eureka:
    port: ${server.port}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        prefer-same-zone-eureka: false
server:
    port: 8092
spring:
    application:
          name: zuulservice
zuul:
    routes:
        usercenter:
            path: /usercenter/**
            serviceId: usercenter